import subprocess
import os

# List of intermediate file extensions generated by xelatex
intermediate_extensions = [
    '.aux', '.log', '.out', '.toc', '.nav', '.snm', '.vrb', '.fls', '.fdb_latexmk', '.synctex.gz'
]

# Base filename
base_filename = 'main'

# Directory containing the files
directory = '.'

# Remove intermediate files
for ext in intermediate_extensions:
    file_path = os.path.join(directory, base_filename + ext)
    if os.path.exists(file_path):
        os.remove(file_path)
        print(f'Removed {file_path}')
    else:
        print(f'File {file_path} does not exist')

# xelatex for 2 times to get the references right
subprocess.run(['xelatex', base_filename + '.tex'])
subprocess.run(['xelatex', base_filename + '.tex'])