import subprocess
import os
import shutil
import time

def compile_tex_to_pdf(tex_filename, output_pdf_filename):
    """
    Compiles a .tex file using xelatex and renames the output PDF file.
    
    Args:
        tex_filename (str): Name of the .tex file (without extension).
        output_pdf_filename (str): Desired name of the output PDF file (with .pdf extension).
    """
    # List of intermediate file extensions generated by xelatex
    intermediate_extensions = [
        '.aux', '.log', '.out', '.toc', '.nav', '.snm', '.vrb', '.fls', '.fdb_latexmk', '.synctex.gz'
    ]

    # Remove intermediate files
    for ext in intermediate_extensions:
        file_path = tex_filename + ext
        if os.path.exists(file_path):
            os.remove(file_path)
            print(f'Removed {file_path}')
        else:
            print(f'File {file_path} does not exist')

    # Compile the .tex file twice to ensure proper referencing
    subprocess.run(['xelatex', tex_filename + '.tex'])
    subprocess.run(['xelatex', tex_filename + '.tex'])

    # Rename the output PDF file to the user-defined name
    output_file = tex_filename + '.pdf'
    if os.path.exists(output_file):
        shutil.move(output_file, output_pdf_filename)
        print(f'Renamed {output_file} to {output_pdf_filename}')
    else:
        print(f'Error: {output_file} does not exist. Compilation may have failed.')

# main tex file name
main_tex_filenam = 'main'
# output file name
output_pdf_filename = 'COMP7802A - Introduction to financial computing.pdf'
# compile the tex file
start_time = time.time()
compile_tex_to_pdf(main_tex_filenam, output_pdf_filename)
print(f'Compilation finished in {time.time() - start_time:.2f} seconds')