user:
  initial_cash: 1000000
  style: 'aggressive'

position_ratio:
  max_aggressive: 0.9
  min_aggressive: 0.3
  max_conservative: 0.7
  min_conservative: 0.1

stock_list:
  - id: '601857'
    name: '中国石油'
  - id: '601988'
    name: '中国银行'
  - id: '600030'
    name: '中信证券'
  - id: '002415'
    name: '海康威视'
  - id: '603019'
    name: '中科曙光'
  - id: 002594
    name: '比亚迪'
  - id: '600428'
    name: '中远海特'
  - id: '600597'
    name: '光明乳业'
  - id: '600519'
    name: '贵州茅台'
  - id: '002027'
    name: '分众传媒'